spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactionario_db
    username: postgres
    password: p@ssw0rd
    
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
